version: "3.7"

services:
  notif_adzan:
    container_name: notif-adzan
    image: notif-adzan:1.0.0
    environment:
      - REMIND_IN_MINUTE=7
      - MILIS_PER_MINUTE=60000
      - SLACK_CHWEB_HOOK=https://hooks.slack.com/services/xxx
      - MSTEAMS_CHWEB_HOOK=https://gtechdigital.webhook.office.com/webhookb2/xxx
      - LOCATION_COUNTRY=ID
      - LOCATION_CITY=Jakarta
